package:
  name: pronto
  version: "1.1.4"

source:
  url: https://files.pythonhosted.org/packages/9f/8f/975cf87011e0f50233465d3fd90c5e27ef34b8dbffc8719bb66bcb3b87d5/pronto-1.1.4.zip
  sha256: c78d4567e88917b861e8486430515033f2bf524134a6616fa5b9ac3049069ec0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - contexter >=0.1.4
    - chardet >=3.0
    - fastobo >=0.6.0
    - nanoset >=0.1.2
    - networkx >=2.3
    - python-dateutil >=2.8

test:
  imports:
    - pronto
    - pronto.utils
    - pronto.parser
    - pronto.serializers

about:
  home: http://github.com/althonos/pronto
  license: MIT License
  summary: 'Python frontend to ontologies'
  license_family: MIT
