{% set version = "0.2.21" %}
{% set github = "https://github.com/acidgenomics/acidplots" %}

package:
  name: r-acidplots
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: b4b2e02b5bcc84b8afc3595bb5e55e2d203c3cb7e47a2d9b93f16579c034c60a

build:
  noarch: generic
  number: 0

requirements:
  host:
      # Depends:
    - r-base
    - r-basejump >=0.11.22
      # Imports:
    - bioconductor-biocgenerics >=0.32
    - bioconductor-iranges >=2.20
    - r-matrix >=1.2
    - r-rcolorbrewer >=1.1
    - bioconductor-s4vectors >=0.24
    - bioconductor-singlecellexperiment >=1.8
    - bioconductor-summarizedexperiment >=1.16
    - r-upsetr >=1.4
    - r-bioverbs >=0.2.11
    - r-cowplot >=1.0
    - r-ggplot2 >=3.2
    - r-ggrepel >=0.8
    - r-ggridges >=0.5
    - r-goalie >=0.4.0
    - r-matrixstats >=0.55
    - r-pheatmap >=1.0
    - r-rlang >=0.4
      # Suggests:
    - bioconductor-dropletutils >=1.4
    - r-viridis >=0.5
  run:
      # Depends:
    - r-base
    - r-basejump >=0.11.22
      # Imports:
    - bioconductor-biocgenerics >=0.32
    - bioconductor-iranges >=2.20
    - r-matrix >=1.2
    - r-rcolorbrewer >=1.1
    - bioconductor-s4vectors >=0.24
    - bioconductor-singlecellexperiment >=1.8
    - bioconductor-summarizedexperiment >=1.16
    - r-upsetr >=1.4
    - r-bioverbs >=0.2.11
    - r-cowplot >=1.0
    - r-ggplot2 >=3.2
    - r-ggrepel >=0.8
    - r-ggridges >=0.5
    - r-goalie >=0.4.0
    - r-matrixstats >=0.55
    - r-pheatmap >=1.0
    - r-rlang >=0.4
      # Suggests:
    - bioconductor-dropletutils >=1.4
    - r-viridis >=0.5

test:
  commands:
    - $R -e "library('acidplots')"

about:
  home: https://acidplots.acidgenomics.com/
  dev_url: "{{ github }}"
  license: MIT
  license_file: LICENSE
  summary: Functions for plotting genomic data.

extra:
  recipe-maintainers:
    - mjsteinbaugh
