{% set version = "1-8e9a7" %}

package:
  name: conterminator 
  version: {{ version|replace("-", ".")  }}

build:
  number: 0

source:
  git_url: https://github.com/martin-steinegger/conterminator
  git_rev: {{ version }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - openmp
    - perl
    - gawk
    - zlib
    - bzip2

  run:
    - openmp
    - gawk
    - zlib
    - bzip2

test:
  commands:
    - conterminator > /dev/null

about:
  home: https://github.com/martin-steinegger/conterminator
  license: GPLv3
  summary: "Conterminator: software to detect contamination in large sequence sets" 

extra:
  skip-lints:
    - uses_vcs_url
    - missing_hash

